### ISSUE TITLE
[nullsafety] defaultPolicies is not initialised due to missing `this.`

### ISSUE THREAD

**Issue by filipproch** [zino-app/graphql-flutter#843]
With the latest `5.0.0-nullsafety.2`

I am having issue with the `graphql_client.dart` crashing due to this line missing `this.`

https://github.com/zino-app/graphql-flutter/blob/7f36a688c09a80c58f77ad925b2d887a5b803376/packages/graphql/lib/src/graphql_client.dart#L30

I think it should be `this.defaultPolicies = defaultPolicies ?? DefaultPolicies();`
(fixed the issue for me locally)

EDIT: exact error
```dart
LateError (LateInitializationError: Field 'defaultPolicies' has not been initialized.)
#0      GraphQLClient.defaultPolicies (package:graphql/src/graphql_client.dart)
package:graphql/src/graphql_client.dart:1
#1      GraphQLClient.query
package:graphql/src/graphql_client.dart:150
```

**Comment by Sander51** [comment]
I was just looking into the same error, for me it happens with 5.0.0-nullsafety.1 as well.

**Comment by dinhthi147** [comment]
me too +1

**Comment by sovannarithsok** [comment]
Waiting your future update.  Just temporary solution like @filipproch fixed locally.

**Comment by 7mada123** [comment]
I am facing the same error on `5.0.0-nullsafety.2`.

**Comment by NickJokic** [comment]
+1

**Comment by micimize** [comment]
fix merged and released as `5.0.0-nullsafety.3`

**Comment by inc16sec** [comment]
Just had this same issue on `graphql_flutter: ^5.0.0-nullsafety.2`. 
Is `graphql_flutter: ^5.0.0-nullsafety.3` released or not yet?.

**Comment by micimize** [comment]
@inc16sec I was referring to `graphql: ^5.0.0-nullsafety.3` – try adding that to your pubspec and see if you still have an issue after cleaning and rerunning. If you do, paste the full stacktrace again

**Comment by inc16sec** [comment]
> @inc16sec I was referring to `graphql: ^5.0.0-nullsafety.3` – try adding that to your pubspec, `flutter clean && flutter packages get`, and see if you still have an issue after cleaning and rerunning. If you do, paste the full stacktrace again

Still the same thing even after adding `graphql: ^5.0.0-nullsafety.3`. This is the error that I got.
`
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: LateInitializationError: Field 'defaultPolicies' has not been initialized.
#0      GraphQLClient.defaultPolicies (package:graphql/src/graphql_client.dart)
package:graphql/src/graphql_client.dart:1
#1      GraphQLClient.query
package:graphql/src/graphql_client.dart:150
`

packages that I have:
```yaml
dependencies:
  graphql_flutter: ^5.0.0-nullsafety.2
  gql: 0.13.0-nullsafety.2
  graphql: ^5.0.0-nullsafety.3
```

**Comment by micimize** [comment]
I slightly tweaked the declaration site in `graphql: ^5.0.0-nullsafety.4` but can't replicate your issue at all. How are you defining your client?

**Comment by inc16sec** [comment]
> I slightly tweaked the declaration site in `graphql: ^5.0.0-nullsafety.4` but can't replicate your issue at all. How are you defining your client?

Now it's working just fine after I've updated `graphql` to `graphql: ^5.0.0-nullsafety.4`. 
Thank you @micimize for the help.

**Comment by inc16sec** [comment]
As for the client, I'm defining it like this.

```Dart
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:graphql_flutter/graphql_flutter.dart';
import 'package:universal_platform/universal_platform.dart';

final GraphQLClient client = getClient(
  uri: UniversalPlatform.isAndroid
      ? 'http://192.168.1.109:4001/graphql'
      : 'http://localhost:4001/graphql',
);

GraphQLClient getClient({
  @required String? uri,
  String? subscriptionUri,
}) {
  Link link = HttpLink(uri!);

  if (subscriptionUri != null) {
    final WebSocketLink websocketLink = WebSocketLink(
      subscriptionUri,
      config: const SocketClientConfig(
        autoReconnect: true,
        inactivityTimeout: Duration(seconds: 30),
      ),
    );

    link = link.concat(websocketLink);
  }

  return GraphQLClient(
    cache: cache,
    link: link,
  );
}

String? uuidFromObject(Object object) {
  if (object is Map<String, Object>) {
    final String typeName = object['__typename'] as String;
    final String id = object['id'].toString();
    if (typeName != null && id != null) {
      return <String>[typeName, id].join('/');
    }
  }
  return null;
}

final GraphQLCache cache = GraphQLCache(
  dataIdFromObject: uuidFromObject,
);

ValueNotifier<GraphQLClient> clientFor({
  @required String? uri,
  String? subscriptionUri,
}) {
  Link link = HttpLink(uri!);
  if (subscriptionUri != null) {
    final WebSocketLink websocketLink = WebSocketLink(
      subscriptionUri,
      config: const SocketClientConfig(
        autoReconnect: true,
        inactivityTimeout: Duration(seconds: 30),
      ),
    );

    link = link.concat(websocketLink);
  }

  return ValueNotifier<GraphQLClient>(
    GraphQLClient(
      cache: cache,
      link: link,
    ),
  );
}

/// Wraps the root application with the `graphql_flutter` client.
/// We use the cache for all state management.
class GraphqlProvider extends StatelessWidget {
  const GraphqlProvider({
    required this.child,
  });

  final Widget child;
//  final ValueNotifier<GraphQLClient> client;

  @override
  Widget build(BuildContext context) {
    return GraphQLProvider(
      client: ValueNotifier<GraphQLClient>(client),
      child: child,
    );
  }
}

```
